---
title: "Lecture 9-21-2026"
---

# Trade and Its Relationship with Peace Cont.

The presence of conflict doesn't mean long lasting hostility/rivalry. Similarly the lack of conlfict doesn't mean a positive relationship between two states. 

- Rivalry (Can be lesser or severe)
    - Frequest Interstate (even militarized) conflict/disputes
    - North/South Korea
    - USA/USSR
- Negative Peace
    - Hostility is still present, however there is rarely any fighting. 
    - Egypt/Israel
- Positive Peace 
    - There is more intentional cooperation between states. 
    - Typically shared membership in international institutions.


## Two Measures of Trade Interdependence 

**Copeland's Trade Exepctation Theory**: High current interdependence, with a positive outlook on the future -> This leads to further peace. Whereas, with high current interdependence and a negative outlook for the future, war becomes MORE likely. The direction of expectations matters more than the level of trade itself. 

Examples of Copelan's theory: Germany (1914, 1939), Japan (1941), Russian/Ukraine(2022). 

**Opium Wars**:

In the 1700's the British had a high demand for Chinese Tea, China wanted virtually nothing in return for tea but British paid them in Silver. The British East India Company grew opium in India and smuggled it into China, eve tually the trade balance flipped and China was paying Britian instead. 

Opdium addicition spread so severely that in 1839 Qing official Lin Zexu confiscated and destroyed over 20,000 chests of British Opium in Canton effectively banning the trade. 

There were two Opium wars that followed. 


**The War of 1812**: 

During the Napoleonic Wars, the British issued the 'Orders in Council' blockading French ports and seizing neutral American ships trading with France. 

British warships practiced impressement stopping American vessels and forcibly conscripting American sailors into the British navy. 

President Madison and Congress conlfuded that trade depdence on Britian had become a tool of coercian not a source of mutual retstraint. 




