---
title: "Lecture 9-2-26"
---

Donald Trump video:

Donald Trump focuses on power as to why the US has a right to own Greenland. Denmark is not willing to defend Greenland and therefore the US should have the right to Greenland as it's territory. 

Trump views the issue of whose territory is Greenland's as an issue of power, the perspective of the citizens of Greenland doesn't matter it's purely a power struggle.

He cares more about what can be done rather than what should be done. 

Mark Carney:

Drops in the Melian Dialoge as step one. Firstly, he states that the world order is no longer based entirely on a rules based order. In order to protect sovreighnty countries like Canada must diversify their partnerships.

# Melian Dialogue

Thucydides' account of Peloponnesian War. "Right as the world goes, is only in question beteween equals in power, while the strong do what they can and the weak suffer what they must."

Soft Power: Can be seen as the global image of a country in terms of a positive or negative view. Japan is ranked high in soft power because of the positive image they have.

---

When a country is very dependant can create a weaker country or reduce bargaining power. 

