---
title: "Lecture 9-9-2026"
---

# Balance of Power & Power Transition 

Balance of Power Theory and power-transition theory are both systemic theories, they explain war and peace with reference to the overall distribution of power across the system. 

## Balance of Power Theory 
1. Disparty in power between major powers can make states feel insecure. 
2. Power imbalance is treated as a paossible cause of war, and bipolarity is presented as potentially producting greater stability. 
3. The balance-of-power tradition developed in multipolar systems where states sought to prevent the emergence of a hegemonic power. 
4. Alliance formation is one method of balancing power. 
5. A fundamental assumption is that states seek power because of security concerns in a self-help system. 

## Power Transition Theory
1. Parity in power between major powers can create insecurity, so power balance is treated as a more probable cause of war. 
2. Power preponderance can produce a more peacful international system, with implications at both the dyadic and systemic levels. 
3. The direct cause of systemic instability is a shift in power between a rising challenger and a dominant status-quo power. 

So in one theory (Balance of Power) two major powers with equal power creates a stable political system, whereas Power Transition Theory states that a single hegemon creates a stable system and countries rising in power create a higher likleihood of conflict. 


## Anarchy 

* Anarchy means the lack of a central authority capable of dictating and enforcing the legitimate use of force above sovereign states. 
* Anarchy does not mean chaos or complete abscense of order, international orders can and do exist. 
* Even realist theories recognize that mechanisms such as the balance of power can create forms of international order. 
* Anarchy differentiates international politics from domestic politics, where hierarchical enforcement mechanisms normally exist. 

## Self Help System 

* Soereignty implies that there are no de jure or de factor enforcement mechanisms reliably superior to states in all matters of security. 
* In a self-help system, states ultimately defend themselves through their own capabilites rather than relying completely on external protection.
* Even when states would prefer mutual restrait such as complete disarmament, each state faces uncertainty about whether the other will remain commited. 

## The Security Dilemma
* A state's attempt at self-defense may involve military build up. 
* Other states cannot be certain whether the increased military power is purely defensive. 
* Even a defensive buildup can therefore increase the security concerns of rivals or opponents. 
* Fear of exploitation creates a cooperation versus defection problem. 
* An arms race is a natural outcome of this dilemma. 

# Realist Paradigms: Classical, Neorealist, and OFfensive Realisst


## Classical Realism 
Key Figures: E. H. Carr and Hans J Morenthau. 

### Core Assumptions 

* State behavior originates in power seeking human nature 
* International and domestic politics share the logic of power politics. 
* Justice, law, and morality are conditioned by power politics. 
* Power balancing and the distribution of power shape international outcomes. 


## Morgenthau's Six Principles of Classical Realism
1. Politics is governed by objective laws rooted in human nature. 
2. Interest is defined in terms of power. 
3. Interest defined as power is unversally valid and constate, althought the meaning and forms of power may change. 
4. The moral significance of political actions must be considered in the context of political consequences. 
5. There is no universially agreed set of moral principals among states. 
6. The political sphere is autonomous from legal, moral, or economic spheres, politics should be studied on it's own terms rather than governed by legal or moral guidelines. 


## Neorealism/Structural Realism

Kenneth Waltz 


* States seek power in order to ensure survival under uncertainty reated by anarchy. 
* Great powers are expected to balance rather than bandwagon. 
* Bipolarity is presented as more stable than multipolarity. 

### Differences from Classical Realism

---

## Defensive and Offensive Realism 

The speaker in the video essays is John Mearsheimer, he's an offensive realist. 

### Offensive Realism

* Great powers seek additional power beyond minimal security. 
* The best route to survival is to acquire as much REGIONAL power as possible. 
* Great powers aspire to regional hegemony when oppurtunity exists. 

### Defensive Realism

* States seek enough power to survive and remain secure.
* Power-seeking is justified by survival and security needs. 
* Balancing can punish states with excessive power. 


# Liberal Traditions and Neolberal Institutionalism 

Immanuel Kant's 1795 essay *Perpetual Peace* is an early liveral foundation for the study of international cooperation. 

Kant's three definitive articles for perpetual peace are: republican governance, a federation of free states, and universal hospitality. 

## Idealism: Woodrow Wilson

Woodrow Wilson's April 1917 speech to Congress framed US participation of in WWI in idealist terms: "The world must be made safe for democracy".

## Neoliberal Institutionalism

1. The state system is anarchic 
2. States 

### Roles of Institutions According to Neorealists 

1. Set Standards for State behaivor
2. Definee defectio nand create costs for defection
3. Spread cooperative norms. 
4. Reduce uncertainty about states' intetnionas by revealing private info
5. Resolve disputes
6. reduce transaction costs 





