---
title: "Lecture 8-28-2026"
---

## Hypotheses

1. Rival States vs Non-Rival States
    - In Rival States, population aging is negatively associated with military spending
    - In Rival States population aging is negatively associated with armed forces personnel counts 
    - In Non-Rival States with an aging population, with an already low level of military spending, the same cuts have further negative effects on military spending and lack of external threats mean that these states spend the minimum they can on their military. 

::: {.callout-note}
When testing these hypotheses it's important to find the variables for $x$ and $y$ where $x$ is commonly referred to as the independent variable or explanatory variable. Whereas $y$ is commonly referred to as the dependant variable, the outcome, or the response variable. 
:::

In our Hypotheses we have 3 variables:

- Population age, military spending, and rivalry status. 

Another variable $z$ is considered our moderating variable (or condition), this reveals that the relationship between $x$ and $y$ differs based on the presence of $z$. 

### Operationaliztion 

In this step of research, we want to find empirical patterns in our associations to see if our hypotheses is correct. 

While doing this you have to consider:

- Sample Size (In this hypotheses all countries between 1970-2015)
    - Spacial: Which countries do you select (all African countries?)
    - Temporal: What historical period (Post cold war, pre cold war, pre world war 2?)
- Unit of Analysis
    - USA from 1975 -> 2015
    - China from 1975 -> 2015 
    - Military personnel per 1000 people. 
        - One reason to choose this amount is because countries have a variable population size and therefore comparing purely active personnel as a total count is not a fair comparison to how aggressively a country is staffing it's military. 
- Estimator
    - A statistical platform in which estimate the association between x and y.
    - If our outcome variable is continuous, binary, dichotamous, ordinal, nominal, event count.
- Systematic:
    - Why does military spending change as a result of our other variables?
- Random Noise
    - Effectively we want to ignore random noise that affects our variables but do not have anything to do with our hypothesus.

- Ordinal: 5 multiple choices with an order.
- These are ways to do statistical models. 

::: {.callout-note}
For our final paper we're going to want to inlcude our Operationalization and our Sample. 
:::






