---
title: "lecture 9-23-2026"
---

# Exam 1 Review

Test is 15 questions, 11 multiple choice questions, 4 short answer questions. 



## Review Topics

Sovriegnty: States can determine their own behavior and fate. Any other entity cannot dictate state's behavior. 
    - Internal: Governing themselves internally and having physical boundaries but not international recognition. (Taiwan)
    - External: Having all of internal sovriegnty but also international recognition as a state. 

Ruling Concept of State Interactions, international system is anarchic. There are still rules and ideas that guide international relations but there is no enforcement mechanism. Absence of global police is the concept of anarchy with regards to international state hood. Realism, Neorealism, all accept this assumption. 

The domestic system is considered hierarchical, or there is a central authority within a state. 

Westphalian Treaties in 1648 (Ended 30 year war): Many scholars believe these treaties marked the end of the feudal system and entered us into the modern system that recognized State Sovreighnty, some scholars argue Congress of Vienna was that point or the US Congress declaring independence. 
    - State Sovriegnty is largely considered the origin of the idea of state sovreignty. 

Some theories use system level analysis, state, or leader. 

Neoliberalism, defensive realism are system focused: These ideas argue that because of constraints applied by the system (say international system) a state acts a certain way, this is a system level analysis. Whereas if it's regime focused, then state, or if leader, leader 

* Concept of Power: Melian Dialogue, Power can be defined only by material capabilities, that's why he believed the stronger what they can, the weaker does what they must. Power can only be understood in the realm of state interaction and their relations with eachother. 
    - Dependece of one state on antoher can create leverage, therefore, material capabilities alone cannot fully define the concept of power. 

* Soft Power: A state's ability to achieve it's desired outcomes through attractive means rather than through military or ecnomic coercion. Sometimes considered the power of image. 

* Balance of Power Theory: States are more likely to be peaceful and safe when they have equal power with eachother. 

* Power Transition Theory: States with have power parity have greater uncertainty, and uncertainty increases the liklihood of conflict. The hegemon in the system has challengers, when the challengers power is rising, once the challengers power approaches the hegemon, war is more likely to occur. 

* Classical Realism
 - States should maximize their power, norms and principals misguide state behavior, only power should guide state behavior. 

* Defensive Realism vs Offensive Realism:
    - Defensive Realism (Neorealism) the ultimate goal of state is security and survival
    - Offensive Realists believe states must accrue more power in order to become regional hegemon's which secures adequate security. 
        - Regional Hegemons tend to prevent other hegemons from rising. 

* How International Institutions Among States
    - Reducing Uncertainty
    - Informing States about Future Behavior
    - Punitive mechanisms
    - Reductions in Transaction Costs 


* Concept of Relative Gains
Realists belive that states care about not only their own gains, but also gains relative to their own. If a state gains much more than my state I'm concerned. Neoliberal Institutionalists worry more about absolute gains. 

* Democratic Peace:

Democracies tend not to go to war with eachother. 

* Monatic & Diatic Democractic Peace
    - Democracies tend to be more peaceful overall, monatic explanation of democractic peace. 
    - Democracies have norms of non-violence and think highly of peaceful compromise as opposed to using violence for resolution. Their leaders tend to be socialzed as such. This type of peace lacks empirical evidence
    - With Diatic peace (which does have empirical peace), Democracies rarely fight against eachother. 
        - **The selectorate theory**: Democractic leaders have an incentive to deliver war victories as this is a public good, to an autocractic leader he can deliver it to the few that keep him in power as a private good. Democractic leaders have a greater incentive therefore to deliver better war outcomes. This is why democractic leaders tend to select easy wins. 
        - Assuming democractic leaders are more accountable to war outcomes, this is why they are more selective in what wars they fight. 
            - Informational Advantage
            - Mobilization Mechanism
            - And others are those mechanisms which yield greater advantages to democracies in war. 


* Oppurtunity Cost mechanism is a signaling mechanism. 

* Security Dilemma 
    - A state's defensive actions can be percieved as offensive actions. The enemy cannot easily distinguish the motives behind military action whether offensive or defensive. A defensive military buildup can be percieved as offensive. 
    - The outcome is often an arms race and further military tension.

TA will adminiter test. 