---
title: "Lecture 8-31-2026"
---

[Reference Notes](https://texastech.instructure.com/courses/98573/modules/items/4676602)

# State, Sovereignty

There is no higher power above the state within it's own territory. Each state should be allowed to dictate it's own behavior. No international actor should be allowed to dictate a state's behavior. This is the concept of Sovereignty.

Anarchy is the absecene of supra-national authority. There is no enforcement mechanism other than the soverignty of the state.

The treaty of Westphalia (1648) is considered as the reference point for the idea of the modern state or when state sovereignty was first recognized.

**A State** is a formal legal system with a central authority that makes and enforces it rules within a defined territory.

**A nation** is a cultural group of people and it not recognized as an international actor.

**Nation-State** is a state that shares within itself a unified social and cultural identity.

**Country** is a common term to refer to a geographic area of a state.

**Extra-Systemic Conflict**: When a state fights against a non-state actor.

---

US achieved internal sovreighty by declaring itself indepdent in 1776, but it lacked external sovreighty (it wasn't recognized by external states). But in 1781 when the Treaty of Paris was signed the US gained external sovreighty. 

Autonomous Territories look like states but are not actually states, e.g. Greenland. 

---

x